-- Create products table
CREATE TABLE products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    "manufacturerId" TEXT NOT NULL,
    prompt TEXT,
    variants JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create config table (single row for system settings)
CREATE TABLE config (
    id INTEGER PRIMARY KEY DEFAULT 1,
    "googleAiApiKey" TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

-- Create activity_logs table
CREATE TABLE activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    action TEXT NOT NULL,
    details JSONB,
    status TEXT NOT NULL
);

-- Enable RLS (Row Level Security) - For now, let's keep it simple or disable for admin
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE config ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

-- Simple policy: allow service role (admin) all access
-- For the public anon key, you might want to allow SELECT on products
CREATE POLICY "Allow public read on products" ON products FOR SELECT USING (true);
